include::config.adoc[]
ifndef::imagesdir[:imagesdir: images]

:url-1: https://www.staticgen.com/
:url-2: https://github.com/asciidoctor/jekyll-asciidoc
:url-3: https://jbake.org/

== Docs-As-Code - Alles unter einem Dach

In der ersten Folge dieser Artikelreihe haben wir Ihnen den Docs-as-Code Ansatz erläutert.
In der zweiten Folge haben wir Ihnen gezeigt, wie Sie durch Automatisierung weitere Build-Schritte erzeugen, die Ihnen die Dokumentation erleichtern.

Dabei lag unser Fokus immer auf einem einzelnen Dokument.
Die Dokumentation Ihres Teams wird hingegen aus einer Vielzahl unterschiedlicher Dokumente bestehen.
Die offentsichtlichen sind die Architekturdokumentation, ein Benutzerhandbuch und ein Entwicklerhandbuch.
Betrachtet man andere Systeme, so spielt auch immer eine Landingpage als Einstieg in das System und ein Blog für aktuelle Informationen eine große Rolle.

Ein Menü zur einfachen Navigation bildet scchliesslich die Klammer um all diese Dokumente (siehe <<diagramm1>>).

In diesem Artikel zeigen wir Ihnen, wie Sie mit Hilfe eines Static Site Generators  alle benötigten Dokumente unter ein Dach bringen und eine Micro-Site für Ihr System bauen.

[[diagramm1]]
.Alle Dokumente unter einem Dach
include::ppt/slides.pptx.ad[tags=components]

=== Anforderungen

Bevor wir uns der eigentlichen Lösung zuwenden, sollten wir zumindest grob die Anforderungen skizziert haben.

Die meisten oben aufgeführten Dokumente können wir mit dem schon besprochenen Docs-as-Code Ansatz prima erzeugen. Wir benötigen also ein System, welches den Docs-as-Code Ansatz mit AsciiDoc unterstützt.

Beim Schreiben mit AsciiDoc steht der Content im Vordergrund, nicht das Layout und die Optik.
Eine Landingpage muss jedoch optisch ansprechend aufgebaut sein.
Das System muss also z.B. reines HTML für möglichst viel Freiheit bei der Gestaltung einer Landingpage erlauben.

Und auch ein Blog hat spezielle Anforderungen. So benötigt ein Blog nicht nur die Darstellung der einzelnen Artikel (was in AsciiDoc sehr gut geht), sondern auch eine Auflistung aller Artikel nach Datum oder nach Kategorien/Tags.

Dokumentieren wir eine Bibliothek, die in mehreren Versionen produktiv im Einsatz ist, so muss auch unsere Dokumentation dem Rechung tragen und in allen unterstützten Versionen vorliegen.

Nicht zuletzt benötigen wir eine Seitenübergreifende Suche.
Strg+F reicht für eine einzelne Seite aus, für eine Dokumentations-Site benötigen wir etwas ausgefeilteres.

=== Static Site Generator (SSG)

Sie können alle oben genannten Anforderungen mit einem Static Site Generator lösen.
Die statische Seite bietet dabei den Vorteil, dass sie selbst keine Anforderungen an ein spezielles Hosting mitbringt und durch die fehlende Dynamik sehr schnell ist.
Sie besteht einfach nur aus statischen HTML Seiten, die sogar aus einem lokalen Verzeichnis aufgerufen werden können.

Der Generator kümmert sich dabei um die "Dynamik".
Jedesmal, wenn Sie eine Änderung an Ihrer Site vornehmen, kümmert er sich um das korrekte Einhängen Ihrer Dokumente in die Navigation, Verknüpfung von Seitenelementen (z.B. ein kleines Autorenprofil für jeden Blog-Artikel) und die Neugenerierung von Übersichtsseiten.

Durch diese Neugenerierung bei jeder Änderung, die Sie von Ihrem Code ja kennen, wird ein dynamisches Blog zu einer statischen Site.

Dieser Ansatz macht Ihre Dokumentation auch extrem schnell, denn statische Seiten benötigen beim Ausliefern an den Browser keine Datenbankzugriffe oder andere Logik.

=== Die Wahl eines SSG

Auf https://staticgen.com[staticgen.com] sind ca. 250 Static Site Generators mit ein paar Attributen aufgeführt.
Genannt ist die Sprache der Implementierung und die Beliebtheit in GithUb-Sternchen.
Die Unterstützung des Markup-Typs ist nicht genannt, weshalb wir für Sie ein wenig recherchiert haben und zu der in <<ssgs>> gezeigten Auswahl gekommen sind.
All diese SSGs unterstützen AsciiDoc und somit unseren Docs-as-Code Ansatz.

==== HUGO

Hugo ist in Go geschrieben und ist dadurch extrem schnell.
Das trägt zur Beliebtheit dieses SSGs bei.
AsciiDoctor wird als externes Tool eingebunden und hebt diesen Vorteil zum Teil dadurch wieder auf.
Für ein reines Java-Projekt ist Hugo mit seiner Implementierung in Go allerdings auch eher der Exot.

====  Antora

Antora ist nicht nur ein SSG, Antora bringt auch einen Git Client mit und kann somit Dokumentation aus verschiedenen Git-Repositories automatisch einsammeln und entsprechend der Versionstags in verschiedenen Versionen generieren.
Es ist das jüngste Projekt von Dan Allen, dem Kopf hinter Asciidoctor.
Damit ist es nicht verwunderlich, dass die AsciiDoc Unterstützung perfekt ist.
Die Leistungsfähigkeit hat Antora schon durch den Einsatz bei größeren Open Source projekten bewiesen.
Eine Landing Page oder ein Blog unterstützt es jedoch nicht, so dass man diese Elemente durch andere Werkzeuge bei Bedarf abdecken müsste.
Antora ist mit Node.js realisiert.

==== Jekyll

Jekyll liegt in der Beliebtheit knapp vor HUGO (gemessen an den GitHub-Sternchen).
Out of the Box wird MarkDown unterstützt.
Das Asciidoctor-Projekt stellt {url-1}[ein Plugin] zur Verfügung mit dem Jekyll nach einer kleinen Konfiguration auch sehr gut AsciiDoc unterstützt.
Durch ein vielfältiges Angebot an Themes kommen Sie mit Jekyll schnell zu guten Ergebnissen.
So ist z.B. unsere WebSite https://docs-as-co.de[docs-as-co.de] mit Jekyll und AsciiDoc aufgebaut.
Jekyll ist, wie Asciidoctor, in Ruby geschrieben.

==== jBake

{url-3}[jBake] scheint eher der unbekannte Champion zu sein, weshalb wir im Folgenden unseren Ansatz mit jBake detaillierter vorstellen werden.
jBake unterstützt AsciiDoc direkt, ist als Command-Line-Tool, Maven und Gradle Plugin und als Library verfügbar.
Durch die Unterstützung verschiedener Template-Engines (Freemarker, Groovy, Thymeleaf and Jade) ist jBake sehr flexibel.
Für ein Java-Projekt ist der größte Vorteil wohl die Implementierung in Java und die perfekte Integration mit Maven und Gradle.

[[ssgs]]
.Ausgewählte Static Site Generators (Quelle: {url-2}[staticgen.com]
include::ppt/slides.pptx.ad[tags=overview]

=== Umsetzung einer Site mit jBake

In den ersten Teilen haben wir als Build-Tool schon Gradle verwendet.
Da jBake über eine entsprechende Gradle Integration verfügt, ist die erste Umsetzung der Site trivial:

[source,groovy]
----
include::../../build.gradle[tags=jbakeplugin;jbakeconfig]
----

Auch hier verwenden wir wieder Asciidoctor mit dem Diagram-Plugin um PlantUML für Diagramme verwenden zu können.

Wenn Sie die ersten Teile der Folge aufmerksam verfolgt haben, wird Ihnen auffallen, dass wir in dieser Konfiguration `src/site` und nicht `src/docs` referenzieren.
In der Praxis hat sich gezeigt, dass es durchaus Sinn macht, die Site von der eigentlichen Dokumentation zu trennen.
So erstellen Sie z.B. Ihre arc42 Dokumentation klassisch mit einem Master-Template, welches alle Unterkapitel per `include` referenziert.
Das Ergebnis ist ein großes Dokument.

In der Site funktioniert die Navigation jedoch besser, wenn Sie jedes Kapitel in der Top-Level-Navigation einzeln aufführen.
Über die Trennung von Dokumentation (`src/docs`) und Site (`src/site`) ist das kein Problem.
Sie legen einfach - ähnlich wie das arc42 Master-Template - für jede Seite ein Dokument an, welches auf beliebige Fragmente Ihrer Dokumentation per `include` verweist.
Durch diesen Ansatz bauen Sie die Struktur Ihrer Site getrennt von der Dokumentation auf und bekommen mehr flexibilität.


Die direkte Integration als Gradle Plugin, Java als Implementierungssprache und der Einsatz von Groovy

== Fazit

[austauschen]
----
Nachdem wir Ihnen im https://www.informatik-aktuell.de/management-und-recht/projektmanagement/docs-as-code-die-grundlagen.html[ersten Artikel] unserer Docs-as-Code Reihe zeigten, wie Sie mit AsciiDoc und https://arc42.org[arc42] den Docs-as-Code Ansatz für Ihre Architekturdokumentation umsetzen können, haben wir Ihnen in dieser Folge einen Einblick gegeben, wie Sie aus diesem Ansatz noch mehr machen können, indem Sie weitere Schritte der Dokumentationserstellung in Ihren Build integrieren.

Das Open-Source Tool docToolchain unterstützt Sie dabei und bietet die oben genannten Build-Schritte als vorgefertigte Tasks.

In der nächten Folge zeigen wir Ihnen, wie Sie verschiedene Dokumentationsartefakte zu einer Website zusammenführen und somit alles unter ein Dach bringen.

Noch mehr Informationen finden Sie in der Zwischenzeit auch auf https://docs-as-co.de[Docs-as-Co.de], diesen Artikel als Docs-as-Code Version auf https://github.com/docToolchain/ia-artikel-folge-2[github.com/docToolchain] und die Dokumentation von docToolchain auf https://doctoolchain.github.io/docToolchain/[doctoolchain.github.io].

In diesem Sinne viel Erfolg mit Docs-as-Code.
----

